controller_manager:
    ros__parameters:
        update_rate: 50 # Hz

        joint_state_broadcaster:
            type: joint_state_broadcaster/JointStateBroadcaster

        joint_trajectory_controller:
            type: joint_trajectory_controller/JointTrajectoryController

        # velocity_controller:
        #     type: velocity_controllers/JointGroupVelocityController

joint_trajectory_controller:
    ros__parameters:
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
            - joint_6

        command_interfaces:
            - position
            # - velocity

        state_interfaces:
            - position
            - velocity

        open_loop_control: false

        allow_nonzero_velocity_at_trajectory_end: true



velocity_controller:
    ros__parameters:
        joints:
            - joint_1
            - joint_2
            - joint_3
            - joint_4
            - joint_5
            - joint_6

        command_interfaces:
            # - position
            - velocity

        # state_interfaces:
        #     - position
        #     - velocity

        # allow_nonzero_velocity_at_trajectory_end: false